### ISSUE TITLE
[feat] : 백테스팅 기능 구현

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#13]
### 📝 Description

- 백테스팅 기능을 구현한다.

---

### 📝 Todo

- [x] 백테스팅 관련 DB 설계
- [x] 백테스팅 동작 메서드 구현
- [x] 백테스팅 실행 API 구현
- [ ] 백테스팅 결과 저장 API 구현
