### ISSUE TITLE
[refactor] : 백테스팅 코드 리팩토링

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#16]
### 📝 Description

- 백테스팅 관련 코드를 리팩토링한다.

---

### 📝 Todo

- [x] 메서드 역할 분리
- [x] 메서드명 수정
- [x] List -> s로 변경
- [x] 유틸은 가볍게 변경
- [x] 불필요한 주석 제거
- [x] 합칠 수 있는 코드 합치기
- [x] 성능 테스트
- [x] 중복 거래 문제 해결
- [x] 에러 처리 추가
