### ISSUE TITLE
[feat] : BaseEntity 적용

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#25]
### 📝 Description

- BaseEntity를 적용하여 관리한다.

---

### 📝 Todo

- [x] BaseEntity 추상 클래스 추가
- [x] 엔터티 리팩토링 진행
- [x] 테스트 유저 1, 2, 3 생성
