### ISSUE TITLE
Upbit DB 설계 & 구축

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#3]
### 📝 Description

- Upbit와 관련한 데이터들의 ERD를 설계하고, 실시간으로 데이터를 수집할 수 있는 기능을 구현한다.

---

### 📝 Todo

- [ ] : Upbit DB ERD 설계
- [ ] : Upbit DB 구축
- [ ] : 실시간 데이터 수집 기능 구현
