### ISSUE TITLE
[refactor] : DTO 관련 리팩토링 진행

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#32]
### 📝 Description

- DTO와 관련된 코드 리팩토링을 진행한다.

---

### 📝 Todo

- [x] of 메서드 구현
- [x] toEntity 메서드 구현
- [x] 불필요한 어노테이션 제거
