### ISSUE TITLE
[feat] : 자동매매 API 구현

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#33]
### 📝 Description

- 자동매매와 관련한 API를 구현한다.

---

### 📝 Todo

- [x] 포트폴리오 자동 매매 등록 (POST)
- [x] 포트폴리오 자동 매매 삭제 (DELETE)
- [ ] 거래 로그 조회 (GET)
