### ISSUE TITLE
[feat] : 대시보드 API 구현

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#42]
### 📝 Description

- 대시보드와 관련한 API를 구현한다.

---

### 📝 Todo

- [x] 유저 업비트 잔고 조회 (GET)
- [x] 유저 업비트 보유 코인 조회 (GET)
- [x] 대표 코인 정보 조회 (GET)
- [x] 비트코인 차트 조회 (GET)
