### ISSUE TITLE
[feat] : 차트 API 구현

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#53]
### 📝 Description

- 코인 & 봉 종류에 따른 OHLCV 차트를 조회하는 API를 구현한다.

---

### 📝 Todo

- [x] 차트 조회 요청 시, DB 업데이트 기능 구현
- [x] OHLCV 차트 조회 (GET)
- [x] 차트 선택 지표 데이터 조회 (GET)
