### ISSUE TITLE
[feat] : 딥러닝 모델 연동

### ISSUE THREAD

**Issue by bbbang105** [CSID-DGU/2024-1-SCS4031-01-owl-4#68]
### 📝 Description

- Flask 서버에 띄운 딥러닝 모델을 연동한다. 

---

### 📝 Todo

- [x] 딥러닝 코드 업로드
- [x] 가격 예측 API 구현
- [x] 딥러닝 모델 연동
